user: "{{ lookup('env', 'USER') | default('ezid') }}"
group: "{{ user }}"
app_dir: "{{ lookup('env', 'HOME') | default('ezid') }}"
deploy_dir: "{{ app_dir }}/arksorg"
 
arksorg_repo: 'https://github.com/CDLUC3/arksorg-site.git'
#arksorg_version: 'main'
arksorg_version: 'python3.11'
python_home: '/usr/'
